name: Push File

on: 
  workflow_dispatch

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: youphendriks/bigcat-software@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      with:
        source_file: 'docs/push.md'
        destination_repo: 'youphendriks/bigcat-software-target'
        user_email: 'youp_hendriks@gmail.com'
        user_name: 'youphendriks'
        commit_message: 'GitHub Action'
