name: Push test 

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/service/*.json'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/service/*.json'

jobs:
  webpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install groovy
        run: sudo apt install python

      - name: Generate overview.md
        run: groovy createSitemap.groovy > docs/sitemap.xml

      - name: Commit report
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        run: |
          git remote add upstream youphendriks/bigcat-software-target@main
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/sitemap.xml
          git add docs/index.md
          git add docs/catalog.md
          git add docs/service/*.md
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Updated service Markdown '
              git push
          fi

      - name: Deploy to external repository
        uses: youphendriks/bigcat-software-target@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        with:
          # GitHub Action output files
          source-directory: public/
          destination-github-username: <external org/user name>
          destination-repository-name: <external repository>
          user-email: <your email>
          # It defaults to `main`
          target-branch: "gh-pages"

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
