name: Push File

on: 
  workflow_dispatch

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes to Repository
      uses: tech-thinker/push-to-repo@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      with:
        user-name: "github-actions[bot]"
        user-email: github-actions[bot]@users.noreply.github.com
        source-directory: "docs/push.md"
        destination-github-username: "youphendriks"
        destination-repository-name: "bigcat-software-target"
        target-branch: main
